name: Build Check after merge with own_build keyboard
on:
  push:
    tags:
      - merge-*

env:
  NAME: marksard(merge_action_bot)
  EMAIL: marksard@rocketmail.com
  REPO_FORK: https://github.com/qmk/qmk_firmware.git
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  merge_build:
    runs-on: ubuntu-latest
    container:
      image: docker://qmkfm/base_container:latest
    steps:
    - name: Checkout marksard/qmk_firmware:own_build
      uses: actions/checkout@v2
      with:
        repository: marksard/qmk_firmware
        ref: own_build
        submodules: true
    - name: Merge firmware
      run: |

        git config --global user.name ${NAME}
        git config --global user.email ${EMAIL}        
        # Pass the --rebase-merges option to git rebase by default
        git config --global pull.rebase merges
        # "git checkout master" is unnecessary, already here by default
        git pull --unshallow  # this option is very important, you would get
                              # complains about unrelated histories without it.
                              # (but actions/checkout@v2 can also be instructed
                              # to fetch all git depth right from the start)
        # Add the repo which you forked to the remote and name it as "upstream"
        git remote add upstream ${REPO_FORK}        
        # Fetch the upstream branches to local
        git fetch upstream
        # Merge changes
        # git checkout master
        git merge --no-edit upstream/master

    - name: Build firmware
      run: |

        chmod +x ./_release_own_build.sh
        ./_release_own_build.sh -release

    - name: Merge push
      run: |

        git push origin qmk_firmware

    # success notify
    - name: Slack Notification on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: ci
        SLACK_TITLE: Test Success
        SLACK_COLOR: good

    # error notify
    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_CHANNEL: ci
        SLACK_TITLE: Test Failure
        SLACK_COLOR: danger
