name: Build and Release own_build keyboard
on:
  # 手動実行
  workflow_dispatch:
  # タグ追加で実行
  push:
    tags:
      - release-*
jobs:
  # QMKファームウェア作成
  make_firmware:
    runs-on: ubuntu-latest
    # QMKのコンテナでビルド
    container:
      image: docker://qmkfm/base_container:latest
    steps:
    # QMKリポジトリと使用するブランチを選択
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: marksard/qmk_firmware
        #ref: own_build_0.18.17
        ref: follow_master_confirm_build
        submodules: true

    # 指定したブランチに入れてあるmakeスクリプトを起動
    # via用hexファイルをmakeし個別にzip圧縮し./_releaseフォルダに置く
    - name: Make firmware
      env:
        PIP_ROOT_USER_ACTION: ignore
      run: |
        /usr/bin/python3 -m pip install --upgrade pip setuptools wheel --root-user-action=ignore
        /usr/bin/python3 -m pip install -r /__w/qmk_firmware_hex/qmk_firmware_hex/requirements.txt
        /usr/bin/python3 -m pip install qmk --root-user-action=ignore
        qmk clean -a
        git config --global --add safe.directory /__w/qmk_firmware_hex/qmk_firmware_hex
        git clean -df
        git clean -f
        git checkout .
        chmod +x ./_release_own_build.sh
        ./_release_own_build.sh -via
        ./_release_own_build.sh -viapack

    # 指定したブランチに入れてあるファイルサイズチェック用スクリプトを起動
    - name: Hex file size check
      run: |
        ./_release_own_build.sh -hexcheck

    # このコンテナで作成したファイルを指定したフォルダごとアップロード
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./_release

  # リリース作業
  release:
    # make_firmwareのjobが完了していることを実行条件とする
    needs: [make_firmware]
    runs-on: ubuntu-latest
    steps:
    # Upload artifactでアップロードしたファイルをダウンロード
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware
    # リリースページへの登録
    - name: Upload a new release asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Keyboard firmware ${{ github.ref_name }}
        files: |
                  marksard_treadstone32_rev1_via.zip
                  marksard_treadstone32_lite_via.zip
                  marksard_treadstone32_rev2_via.zip
                  marksard_treadstone48_rev1_via.zip
                  marksard_treadstone48_rev2_via.zip
                  marksard_leftover30_via.zip
                  marksard_rhymestone_rev1_via.zip
                  marksard_treadstone60_via.zip
                  marksard_m0ii040pcb_via.zip
                  marksard_numatray_via.zip
