name: Build and Release own_build keyboard
on:
  push:
    tags:
      - release-*
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    container:
      image: docker://qmkfm/base_container:latest
    steps:
    - name: Checkout marksard/qmk_firmware:own_build
      uses: actions/checkout@v2
      with:
        repository: marksard/qmk_firmware
        ref: own_build
        submodules: true
    - name: Build firmware
        # chmod +x ./_release_own_build.sh
        # ./_release_own_build.sh -release
      run: |
        make treadstone32:via
        make treadstone32/lite:via
        make treadstone48/rev1:via
        make treadstone48/rev2:via
        make marksard/leftover30:via
        make marksard/rhymestone:via
        make marksard/treadstone60:via
        cp ./keyboards/treadstone32/keymaps/via/treadstone32_rev1_lite_via.json ./treadstone32_rev1_lite_via.json
        cp ./keyboards/treadstone48/keymaps/via/treadstone48_rev1_via.json ./treadstone48_rev1_via.json
        cp ./keyboards/treadstone48/keymaps/via/treadstone48_rev2_via.json ./treadstone48_rev2_via.json
        cp ./keyboards/marksard/leftover30/keymaps/via/marksard_leftover30_via.json ./marksard_leftover30_via.json
        cp ./keyboards/marksard/rhymestone/keymaps/via/marksard_rhymestone_rev1_via.json ./marksard_rhymestone_rev1_via.json
        cp ./keyboards/marksard/treadstone60/keymaps/via/marksard_treadstone60_via.json ./marksard_treadstone60_via.json
        cp ./keyboards/marksard/treadstone60/keymaps/via/marksard_treadstone60_alpha_via.json ./marksard_treadstone60_alpha_via.json
        mkdir _release
        zip -r ./_release/treadstone32_rev1_via.zip ./treadstone32_rev1_lite_via.json ./treadstone32_rev1_via.hex
        zip -r ./_release/treadstone32_lite_via.zip ./treadstone32_rev1_lite_via.json ./treadstone32_lite_via.hex
        zip -r ./_release/treadstone48_rev1_via.zip ./treadstone48_rev1_via.json ./treadstone48_rev1_via.hex
        zip -r ./_release/treadstone48_rev2_via.zip ./treadstone48_rev2_via.json ./treadstone48_rev2_via.hex
        zip -r ./_release/marksard_leftover30_via.zip ./marksard_leftover30_via.json ./marksard_leftover30_via.hex
        zip -r ./_release/marksard_rhymestone_rev1_via.zip ./marksard_rhymestone_rev1_via.json ./marksard_rhymestone_rev1_via.hex
        zip -r ./_release/marksard_treadstone60_via.zip ./marksard_treadstone60_via.json ./marksard_treadstone60_alpha_via.json ./marksard_treadstone60_via.hex
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./_release

  release:
    needs: [create_release, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        keyboards: [
          treadstone32_rev1_via, treadstone32_lite_via,
          treadstone48_rev1_via, treadstone48_rev2_via,
          marksard_leftover30_via, marksard_rhymestone_rev1_via,
          marksard_treadstone60_via]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: firmware
    - name: Upload a new release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.keyboards }}.zip
        asset_name: ${{ matrix.keyboards }}.zip
        asset_content_type: application/zip
