name: Build and Release own_build keyboard
on:
  push:
    tags:
      - release-*
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    container:
      image: docker://qmkfm/base_container:latest
    steps:
    - name: Checkout marksard/qmk_firmware:own_build
      uses: actions/checkout@v2
      with:
        repository: marksard/qmk_firmware
        ref: own_build
        submodules: true
    - name: Build firmware
      run: |
        # chmod +x ./_release_own_build.sh
        # ./_release_own_build.sh -release
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./_release

  release:
    needs: [create_release, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        keyboards: [
          treadstone32_rev1_via, treadstone32_lite_via,
          treadstone48_rev1_via, treadstone48_rev2_via,
          marksard_leftover30_via, marksard_rhymestone_rev1_via,
          marksard_treadstone60_via]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: firmware
    - name: Upload a new release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.keyboards }}.zip
        asset_name: ${{ matrix.keyboards }}.zip
        asset_content_type: application/zip
